services:
- type: web
name: whatsapp-bot
runtime: docker
repo: https://github.com/RoyalKatsic1/WhatsApp_Bot
envVars:
    - key: SUDO
sync: false
    - key: WHATSAPP_TOKEN
sync: false
region: oregon
dockerContext: .
dockerfilePath: ./DockerfilePath
version: '1'
